#!/usr/bin/env bash
# This file prints "Hi" after "Best School" on the 9th iteration
n=0
while [ $n -lt 10 ]
do
	if [ $n -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( n++ ))
done
