#!/usr/bin/env bash
# Prints "bad luck" on the 4th iteration and "good luck" of the 8th iteration
n=1
while [ $n -le 10 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( n++ ))
done
