#!/usr/bin/env bash
# checks whether or not the file "school" exists
# checks if the the file is empty or not
# checks if the file is regular or not

if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "school" ]
	then
		echo "school is regular file"
	fi

else
	echo "school file does not exist"
fi
