#!/usr/bin/env bash
#configures the ubuntu server to the following requirements
#	-localhost resolves to 127.0.0.2
#	- facebook resolves to 8.8.8.8
cp /etc/hosts ~/host.new
echo "127.0.0.2		localhost" > host.new
echo "8.8.8.8		facebook.com" >> host.new
cp -f ~/host.new /etc/hosts
